
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    ports:
      - "8080:8080"
    volumes:
      - ./brewing:/brewing
    env_file:
      - .env

  react:
    build:
      context: ./brewing/react-app
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:3000"
    stdin_open: true # keep stdin open even if not attached
