# Cloud Build setting file
# for Google Cloud Build
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _HF_API_KEY: ''
  _DJANGO_SECRET_KEY: ''

# Access secrets directly
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/brew-wing-secret/versions/latest
      env: 'HUGGINGFACE_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/django-secret/versions/latest
      env: 'DJANGO_SECRET_KEY'

steps:
  # backend build and push
  #=========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    entrypoint: 'bash'
    args:
      - "-c"
      - 'docker build --build-arg DJANGO_SECRET_KEY=$$DJANGO_SECRET_KEY --build-arg HUGGINGFACE_TOKEN=$$HUGGINGFACE_TOKEN -t gcr.io/$PROJECT_ID/brewwing-backend:latest .'
    secretEnv: ['HF_API_KEY', 'DJANGO_SECRET_KEY']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/$PROJECT_ID/brewwing-backend:latest'
      ]
  # frontend build and push
  #=========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/brewwing/brewwing-frontend:latest',
        '-f','brewing/react-app/Dockerfile.frontend',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/brewwing/brewwing-frontend:latest'
      ]
  # backend deploy
  #=========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'brewwing-backend',
        '--image', 'gcr.io/$PROJECT_ID/brewwing-backend:latest',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
      ]
  # frontend deploy
  #=========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'brewwing-frontend',
        '--image', 'gcr.io/$PROJECT_ID/brewwing-frontend:latest',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated'
      ]

timeout: 2400s 
