# Cloud Build setting file
# for Google Cloud Build
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  
  # backend build and push
  #=========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        # tag the image
        '-t', 'gcr.io/brewwing/brewwing-backend:latest',
        # dockerfile path
        '-f', 'Dockerfile.backend',
        '.'
      ]
    secretEnv: ['BREW_WING_SECRET']

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/brewwing/brewwing-backend:latest'
      ]
  # frontend build and push
  #=========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/brewwing/brewwing-frontend:latest',
        '-f','brewing/react-app/Dockerfile.frontend',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/brewwing/brewwing-frontend:latest'
      ]
  # backend deploy
  #=========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'brewwing-backend',
        '--image', 'gcr.io/$PROJECT_ID/brewwing-backend:latest',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
      ]
  # frontend deploy
  #=========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'brewwing-frontend',
        '--image', 'gcr.io/$PROJECT_ID/brewwing-frontend:latest',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated'
      ]



availableSecrets:
  secretManager:
    - versionName: "projects/903635083978/secrets/brew-wing-secret/versions/latest"
      env: "BREW_WING_SECRET"

timeout: 1200s 
