# Cloud Build setting file
# for Google Cloud Build
options:
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: "projects/903635083978/secrets/brew-wing-secret/versions/latest"
      env: "brew-wing-secret"

steps:
  
  # backend build and push
  #=========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    secretEnv: ['brew-wing-secret']     
    args:
      - 'build'
      - '--build-arg'
      - 'brew-wing-secret=$$brew-wing-secret'
      - '--tag'
      - 'gcr.io/$PROJECT_ID/brewwing-backend:latest'
      - '--file'
      - 'Dockerfile.backend'
      - '.'           
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/brewwing/brewwing-backend:latest'
      ]
  # frontend build and push
  #=========================================================================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/brewwing/brewwing-frontend:latest',
        '-f','brewing/react-app/Dockerfile.frontend',
        '.'
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'push',
        'gcr.io/brewwing/brewwing-frontend:latest'
      ]
  # backend deploy
  #=========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'brewwing-backend',
        '--image', 'gcr.io/$PROJECT_ID/brewwing-backend:latest',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated',
      ]
  # frontend deploy
  #=========================================================================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'brewwing-frontend',
        '--image', 'gcr.io/$PROJECT_ID/brewwing-frontend:latest',
        '--platform', 'managed',
        '--region', 'us-central1',
        '--allow-unauthenticated'
      ]





timeout: 2400s 
