FROM python:3.10-slim

# set directory to /app
WORKDIR /app

ENV DJANGO_SETTINGS_MODULE=brewing.settings
ENV PORT=8080


# system dependencies
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# copy project files
COPY brewing/ .

# expose port 8080 for the server
EXPOSE 8080

# start the server using gunicorn
CMD ["sh", "-c", "exec uvicorn brewing.asgi:application --bind 0.0.0.0:${PORT:-8080} --workers 3"]



