# Base image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy react-app files
COPY brewing/react-app/ ./

# Install dependencies
RUN npm install

# Build the React app for production
RUN npm run build --verbose

# Expose port for the React app
EXPOSE 8080

# Start the React app using a production-ready server (e.g., serve)
RUN npm install -g serve
CMD ["sh", "-c", "serve -s build -l ${PORT:-8080}"]
